In [5]:
!pip install -qU langchain-text-splitters langchain-community langchain-openai langchain-chroma chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 3.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 34.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 611.1/611.1 kB 30.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 75.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.2/284.2 kB 17.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 73.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 91.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 kB 11.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.3/65.3 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.0/119.0 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 49.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 459.8/459.8 kB 25.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 89.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.8/454.8 kB 27.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 6.5 MB/s eta 0:00:00
  Building wheel for pypika (pyproject.toml) ... done

In [6]:
import langchain_text_splitters,langchain_core
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.document_loaders import TextLoader
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

In [12]:
import pandas as pd

books = pd.read_csv("/content/books_cleaned.csv")

In [13]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [14]:
# Langchain data loader don't work with pandas so we convert the tagged description to a file text
books['tagged_description'].to_csv("tagged_description.txt",
                                   sep="\n",
                                   index = False,
                                   header=False
                                   )

In [15]:
raw_documents = TextLoader("tagged_description.txt").load()
# To Ensure no overlapping and split only on the separator
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0,separator = "\n")
documents = text_splitter.split_documents(raw_documents)

Streaming output truncated to the last 5000 lines.
WARNING:langchain_text_splitters.base:Created a chunk of size 1483, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 221, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1135, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 722, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 668, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 765, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 606, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 570, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 965, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 857, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1032, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 189, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 367, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 495, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 652, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 348, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 733, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 525, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1015, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 970, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 204, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 688, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 544, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 242, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 207, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 376, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 931, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 564, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 854, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 715, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 749, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 712, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 324, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 241, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1088, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 723, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 245, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 227, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 704, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1912, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 395, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 485, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 622, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 559, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 556, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 386, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 229, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 425, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 418, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 284, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 166, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 624, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 2616, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1580, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 389, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 994, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 847, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 263, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 336, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1530, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 213, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 291, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 2030, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 396, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1619, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 698, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 822, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 354, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 843, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1189, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 195, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 508, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 663, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1282, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 260, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 242, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 215, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 198, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1277, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 198, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1056, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 378, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 269, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 177, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 225, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 222, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 784, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 969, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 613, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 163, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 757, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 289, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 245, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 963, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 232, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 843, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 786, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 648, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 984, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 799, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 193, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1163, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 253, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 203, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1058, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 246, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 875, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 817, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 378, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 755, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 569, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 628, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 868, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 620, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 621, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1084, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 2762, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1033, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 758, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 773, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 634, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1010, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 189, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1064, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 492, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 795, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 699, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 485, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 372, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 275, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1224, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 223, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 345, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 657, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 199, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 767, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 553, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 227, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 233, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 590, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 238, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 299, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 726, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1805, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1017, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 684, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 739, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 236, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 449, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 472, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 922, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 220, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 162, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 967, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 477, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 220, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 645, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 676, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 712, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 799, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 854, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 670, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 211, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 854, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 275, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 760, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 796, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 679, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 927, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 733, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 868, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 931, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 772, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 770, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 335, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 649, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 1771, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 534, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 824, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 261, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 599, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 486, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 969, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 275, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 554, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 491, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 844, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 876, which is longer than the specified 0
WARNING:langchain_text_splitters.base:Created a chunk of size 670, which is longer than the specified 0

In [16]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [18]:
from langchain.embeddings import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

<ipython-input-18-6c71506a9d51>:3: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [19]:
# Storing the descriptions in the chroma db

db = Chroma.from_documents(documents, embedding_model)

In [20]:
query = "A book to teach children about nature"

docs = db.similarity_search(query,k=10)

docs

[Document(id='a89e7e04-45e2-434f-90d9-2b2786f6a3d2', metadata={'source': 'tagged_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='d943bdb4-3c2e-493c-9636-4099f90cfa8c', metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='14dd8640-cf0f-44f9-8d77-bcc9b4f10758', metadata={'source': 'tagged_description.txt'}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='b2977d83-2fa7-490e-82ff-4fb141d774b7', metadata={'source': 'tagged_description.txt'}, page_content="9780060959036 Barbara Kingsolver's fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel's intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place."),
 Document(id='33a09347-2087-4b13-967b-949d6f6ae83d', metadata={'source': 'tagged_description.txt'}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='d60703c1-c9ed-4c92-acba-8f4019a9acec', metadata={'source': 'tagged_description.txt'}, page_content="9780374522599 The Control of Nature is John McPhee's bestselling account of places where people are locked in combat with nature. Taking us deep into these contested territories, McPhee details the strageties and tactics through which people attempt to control nature. Most striking is his depiction of the main contestants: nature in complex and awesome guises, and those attempting to wrest control from her - stubborn, sometimes foolhardy, more often ingenious, and always arresting characters."),
 Document(id='97649735-f018-4075-a2ad-c4e0fa45c20d', metadata={'source': 'tagged_description.txt'}, page_content='9780786819119 Charming illustrations and playful rhythmic verse make real-life learning fun by taking babies and toddlers on an adventurous discovery of water and its many sources. Squeezable and floatable, Water, Water, Everywhere can be enjoyed in and out of the tub.'),
 Document(id='ed02d9d3-9075-4a09-9e7f-60fb462fc3b0', metadata={'source': 'tagged_description.txt'}, page_content="9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author's father].' 'BL. 1986 Children's Editors' Choices (BL) Children's Choices for 1987 (IRA/CBC) Notable 1986 Childrens' Trade Books in Social Studies (NCSS/CBC) 1986 Children's Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"),
 Document(id='75531231-e4aa-44f2-ae06-4962a754d220', metadata={'source': 'tagged_description.txt'}, page_content='"9781593851170 ""Comprehensive and up to date, this tightly edited volume belongs on the desks of researchers and students in developmental psychology, comparative psychology, animal behavior, and evolutionary psychology, and will also be of interest to anthropologists. It is a richly informative text for advanced undergraduate- and graduate-level courses.""--BOOK JACKET."'),
 Document(id='2dea6c1b-a331-4e6c-b361-525df7d6c09b', metadata={'source': 'tagged_description.txt'}, page_content="9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat's community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it's hard to evade questions forever. Children's Choices for 1991 (IRA/CBC)VOYA's Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award")]

In [22]:
# We got to return the title and the author not the full description so we use the isbn13

books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [29]:
# creating a function for the recommendations

def get_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db.similarity_search(query, k = 50) # Retrieve the top 50 books with similarity search

    books_list = [] #list of isbns

    for i in range(0, len(recs)): # Looping on the 50 retrieved documents
    # remove any quotes and split the first token "isbn13" and adding them to the list
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)].head(top_k) #Searching throught the df with the top isbns and returning only 10

In [30]:
get_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
59,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,2095.0,The Family Way,9780007151240 It should be the most natural th...
324,9780060959036,0060959037,Prodigal Summer,Barbara Kingsolver,Fiction,http://books.google.com/books/content?id=06IwG...,Barbara Kingsolver's fifth novel is a hymn to ...,2001.0,4.00,444.0,85440.0,Prodigal Summer: A Novel,9780060959036 Barbara Kingsolver's fifth novel...
334,9780060976118,006097611X,Operation Wandering Soul,Richard Powers,Fiction,http://books.google.com/books/content?id=nIGIm...,"Highly imaginative and emotionally powerful, t...",1994.0,3.62,352.0,366.0,Operation Wandering Soul,9780060976118 Highly imaginative and emotional...
383,9780061144899,0061144894,When the Heart Waits,Sue Monk Kidd,Religion,http://books.google.com/books/content?id=JlP91...,From the Bestselling Author of The Secret Life...,2006.0,4.17,240.0,2141.0,When the Heart Waits: Spiritual Direction for ...,9780061144899 From the Bestselling Author of T...
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,Racso and the Rats of NIMH,"9780064402453 ‘Racso, a brash and boastful lit..."
406,9780064403870,0064403874,"R-T, Margaret, and the Rats of NIMH",Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=WTHHH...,"When Margaret and her younger brother, Artie, ...",1991.0,3.52,272.0,631.0,"R-T, Margaret, and the Rats of NIMH",9780064403870 When Margaret and her younger br...
407,9780064404419,0064404412,The Rainbow People,Laurence Yep,Juvenile Fiction,http://books.google.com/books/content?id=5AHwq...,"""Culled from 69 stories collected in a [1930s]...",1992.0,3.75,208.0,202.0,The Rainbow People,"9780064404419 ""Culled from 69 stories collecte..."
416,9780064406925,006440692X,Winter on the Farm,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=IvlKH...,The Little House books tell the story of a lit...,1997.0,4.13,32.0,400.0,Winter on the Farm,9780064406925 The Little House books tell the ...
427,9780064434874,0064434877,Christmas in the Big Woods,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=FT1Yp...,"Long ago, a little girl named Laura Ingalls li...",1997.0,4.19,32.0,2062.0,Christmas in the Big Woods,"9780064434874 Long ago, a little girl named La..."
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,The Deer in the Wood,9780064434980 Even the youngest child can enjo...

In [28]:
get_semantic_recommendations("sci-fi books with AI")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
130,9780060525101,006052510X,Happiness,Will Ferguson,Fiction,http://books.google.com/books/content?id=4B2EY...,Why would there be a contract out on Edwin de ...,2003.0,3.78,320.0,2191.0,Happiness: A Novel,9780060525101 Why would there be a contract ou...
147,9780060556525,0060556528,Gold,Isaac Asimov,Fiction,http://books.google.com/books/content?id=td_ul...,Gold is the final and crowning achievement of ...,2003.0,3.99,416.0,2393.0,Gold: The Final Science Fiction Collection,9780060556525 Gold is the final and crowning a...
254,9780060841867,0060841869,The Curtain,Milan Kundera,Literary Collections,http://books.google.com/books/content?id=JCDXP...,Traces the author's personal view of the histo...,2006.0,3.96,176.0,1351.0,The Curtain: An Essay in Seven Parts,9780060841867 Traces the author's personal vie...
845,9780143036241,0143036246,The Christians and the Fall of Rome,Edward Gibbon,History,http://books.google.com/books/content?id=DAeWA...,Penguin brings you the works of the great thin...,2005.0,3.57,96.0,202.0,The Christians and the Fall of Rome,9780143036241 Penguin brings you the works of ...
846,9780143036357,0143036351,Why I Write,George Orwell,Language Arts & Disciplines,http://books.google.com/books/content?id=6I_qP...,"Throughout history, some books have changed th...",2005.0,4.03,120.0,5874.0,Why I Write,"9780143036357 Throughout history, some books h..."
859,9780143037576,0143037579,Fear and Trembling,Søren Kierkegaard,Philosophy,http://books.google.com/books/content?id=acFp6...,"The perfect books for the true book lover, Pen...",2005.0,4.00,160.0,13333.0,Fear and Trembling,9780143037576 The perfect books for the true b...
897,9780156027595,0156027593,The Cyberiad,Stanislaw Lem,Fiction,http://books.google.com/books/content?id=kWElP...,Trurl and Klaupacius are constructor robots wh...,2002.0,4.18,295.0,7512.0,The Cyberiad,9780156027595 Trurl and Klaupacius are constru...
937,9780156932509,0156932504,The Uses of Literature,Italo Calvino,Literary Criticism,http://books.google.com/books/content?id=INlwz...,This essay collection discusses literature in ...,1987.0,4.07,341.0,887.0,The Uses of Literature: Essays,9780156932509 This essay collection discusses ...
1070,9780231124270,0231124279,The Poetry of Sylvia Plath,Claire Brennan,Literary Criticism,http://books.google.com/books/content?id=TSrx1...,Liquid Metal brings together 'seminal' essays ...,1999.0,4.23,202.0,25.0,The Poetry of Sylvia Plath,9780231124270 Liquid Metal brings together 'se...
1255,9780312423131,0312423136,Galatea 2.2,Richard Powers,Fiction,http://books.google.com/books/content?id=ttcEu...,"The protagonist, a Humanist-in-Residence at th...",2004.0,3.72,329.0,2063.0,Galatea 2.2: A Novel,"9780312423131 The protagonist, a Humanist-in-R..."
1271,9780312852535,0312852533,The Humanoids,Jack Williamson,Fiction,http://books.google.com/books/content?id=vPSl0...,A classic science fiction novel features human...,1996.0,3.75,299.0,880.0,The Humanoids: A Novel,9780312852535 A classic science fiction novel ...
1351,9780316281331,0316281336,"The World Treasury of Physics, Astronomy, and ...",Timothy Ferris;Clifton Fadiman,Education,http://books.google.com/books/content?id=zryXG...,The writings of more than 60 authors including...,1993.0,4.12,859.0,361.0,"The World Treasury of Physics, Astronomy, and ...",9780316281331 The writings of more than 60 aut...
1368,9780316919890,0316919896,A Supposedly Fun Thing I'll Never Do Again,David Foster Wallace,Humor,http://books.google.com/books/content?id=Qkhpv...,In this exuberantly praised book - a collectio...,1997.0,4.27,353.0,702.0,A Supposedly Fun Thing I'll Never Do Again: Es...,9780316919890 In this exuberantly praised book...
1418,9780330491198,0330491199,The Hitchhiker's Guide to the Galaxy,Douglas Adams,"Dent, Arthur (Fictitious character)",http://books.google.com/books/content?id=S062Q...,Adams's beloved and enduring sci-fi/comedy cla...,2002.0,4.22,180.0,2918.0,The Hitchhiker's Guide to the Galaxy,9780330491198 Adams's beloved and enduring sci...
1449,9780345346292,0345346297,The Dragons of Eden,Carl Sagan,Nature,http://books.google.com/books/content?id=Nmkoz...,The well-known astronomer and astrobiologist s...,1977.0,4.17,271.0,14974.0,The Dragons of Eden: Speculations on the Evolu...,9780345346292 The well-known astronomer and as...
1489,9780345439499,034543949X,The Best of Lester Del Rey,Lester Del Rey,Fiction,http://books.google.com/books/content?id=3LZ6P...,A collection of classic stories by the cofound...,2000.0,3.80,320.0,73.0,The Best of Lester Del Rey,9780345439499 A collection of classic stories ...
1744,9780375826894,0375826890,Code Word Kangaroo,George Edward Stanley,Juvenile Fiction,http://books.google.com/books/content?id=k_WF6...,"Gadgets, girls, and bad guys—Adam Sharp has ev...",2004.0,4.33,48.0,4.0,Code Word Kangaroo,"9780375826894 Gadgets, girls, and bad guys—Ada..."
1754,9780380710843,0380710846,Caesar's Women,Colleen McCullough,Fiction,http://books.google.com/books/content?id=yFK8F...,The fourth novel of the Masters of Rome series...,1997.0,4.24,943.0,5277.0,Caesar's Women,9780380710843 The fourth novel of the Masters ...
1814,9780385333788,0385333781,Player Piano,Kurt Vonnegut,Fiction,http://books.google.com/books/content?id=oIyVN...,Kurt Vonnegut's first novel spins the chilling...,1999.0,3.87,341.0,38620.0,Player Piano,9780385333788 Kurt Vonnegut's first novel spin...
1817,9780385333900,0385333900,Jailbird,Kurt Vonnegut,Fiction,http://books.google.com/books/content?id=QP-4s...,"A master of contemporary American literature, ...",1999.0,3.81,310.0,17241.0,Jailbird,9780385333900 A master of contemporary America...
1911,9780393320039,0393320030,On Becoming a Novelist,John Gardner,Language Arts & Disciplines,http://books.google.com/books/content?id=Go68K...,An indispensable reference for anyone who hope...,1999.0,4.11,150.0,2241.0,On Becoming a Novelist,9780393320039 An indispensable reference for a...
1957,9780394704371,0394704371,The Will to Power,Friedrich Wilhelm Nietzsche;Walter Arnold Kauf...,Philosophy,http://books.google.com/books/content?id=jRa6g...,Offers a selection from the author's notebooks...,1968.0,4.05,575.0,7692.0,The Will to Power,9780394704371 Offers a selection from the auth...
2012,9780425161739,0425161730,Virtual Vandals,Tom Clancy;Steve R. Pieczenik;Diane Duane,Fiction,http://books.google.com/books/content?id=gU7Ju...,Here comes a Clancy first: a new series of nov...,1999.0,4.00,192.0,3236.0,Virtual Vandals,9780425161739 Here comes a Clancy first: a new...
2235,9780441013432,0441013430,Old Twentieth,Joe Haldeman,Fiction,http://books.google.com/books/content?id=0RTfm...,Jacob Brewer confronts a dangerous sentient ma...,2006.0,3.53,285.0,1138.0,Old Twentieth,9780441013432 Jacob Brewer confronts a dangero...
2405,9780451450647,0451450647,Robot Visions,Isaac Asimov,Fiction,http://books.google.com/books/content?id=6lYJA...,"Spanning Asimov's fifty-year career, this coll...",1991.0,4.22,496.0,7425.0,Robot Visions,9780451450647 Spanning Asimov's fifty-year car...
2406,9780451452580,0451452585,Dealing in Futures,Joe Haldeman,Fiction,http://books.google.com/books/content?id=Y5sBA...,This collection contains eleven of the author'...,1993.0,3.72,352.0,185.0,Dealing in Futures,9780451452580 This collection contains eleven ...
2478,9780471272427,0471272426,The Skeptic's Dictionary,Robert Carroll,Science,http://books.google.com/books/content?id=h7m6N...,A wealth of evidence for doubters and disbelie...,2003.0,4.03,446.0,522.0,The Skeptic's Dictionary: A Collection of Stra...,9780471272427 A wealth of evidence for doubter...
2491,9780471782476,0471782475,The Science of Stephen King,Lois H. Gresh;Robert Weinberg,Literary Criticism,http://books.google.com/books/content?id=ns5kJ...,Introduction: Where Science and Fiction Inters...,2007.0,3.49,272.0,58.0,The Science of Stephen King: From Carrie to Ce...,9780471782476 Introduction: Where Science and ...
2518,9780486424620,0486424626,The Trojan Women and Hippolytus,Euripides,Drama,http://books.google.com/books/content?id=dPomD...,Two literary classics of human self-understand...,2002.0,3.56,64.0,31.0,The Trojan Women and Hippolytus,9780486424620 Two literary classics of human s...
2532,9780486447407,0486447405,The Worm Ouroboros,E. R. Eddison;Keith Henderson,Fiction,http://books.google.com/books/content?id=qh_y0...,"""The greatest and most convincing writer of 'i...",2006.0,3.70,446.0,2835.0,The Worm Ouroboros,"9780486447407 ""The greatest and most convincin..."
2551,9780515135961,0515135968,Shadow Game,Christine Feehan,Fiction,http://books.google.com/books/content?id=yzzts...,"From the ""New York Times"" bestselling author c...",2003.0,4.12,323.0,15364.0,Shadow Game,"9780515135961 From the ""New York Times"" bestse..."
2700,9780553345841,0553345842,The Mind's I,Douglas R. Hofstadter;Daniel Clement Dennett,Philosophy,http://books.google.com/books/content?id=hz22Q...,"Brilliant, shattering, mind-jolting, ""The Mind...",1982.0,4.14,512.0,4715.0,The Mind's I: Fantasies and Reflections on Sel...,"9780553345841 Brilliant, shattering, mind-jolt..."
2776,9780553585803,0553585800,Forty Signs of Rain,Kim Stanley Robinson,Fiction,http://books.google.com/books/content?id=TI18I...,In the first installment of a trilogy of eco-t...,2005.0,3.54,393.0,2956.0,Forty Signs of Rain,9780553585803 In the first installment of a tr...
2791,9780553803525,0553803522,Social Intelligence,Daniel Goleman,Psychology,http://books.google.com/books/content?id=akQLx...,The best-selling author of Emotional Intellige...,2006.0,3.98,403.0,9957.0,Social Intelligence: The New Science of Human ...,9780553803525 The best-selling author of Emoti...
2961,9780670886586,0670886580,Haroun and the Sea of Stories,Salman Rushdie,Fiction,http://books.google.com/books/content?id=O-6nP...,It all begins with a letter. Fall in love with...,1999.0,4.01,224.0,21536.0,Haroun and the Sea of Stories,9780670886586 It all begins with a letter. Fal...
3038,9780674644847,0674644840,Origins of the Modern Mind,Merlin Donald,Medical,http://books.google.com/books/content?id=4Sk4v...,This bold and brilliant book asks the ultimate...,1991.0,4.17,424.0,88.0,Origins of the Modern Mind: Three Stages in th...,9780674644847 This bold and brilliant book ask...
3115,9780679767473,0679767479,The Untouchable,John Banville,Fiction,http://books.google.com/books/content?id=lOeXp...,A winner of the Lannan Literary Award and a Pu...,1998.0,3.96,367.0,2077.0,The Untouchable,9780679767473 A winner of the Lannan Literary ...
3409,9780743474764,0743474767,The Best of Ray Bradbury,Ray Bradbury,Comics & Graphic Novels,http://books.google.com/books/content?id=6K-_A...,Collects top adaptations of the popular scienc...,2003.0,4.07,162.0,297.0,The Best of Ray Bradbury: The Graphic Novel,9780743474764 Collects top adaptations of the ...
3619,9780765300355,0765300354,Legends,Robert Silverberg,Fiction,http://books.google.com/books/content?id=pr6Rn...,A collection of original short novels by such ...,2001.0,3.92,717.0,333.0,Legends: Stories By The Masters of Modern Fantasy,9780765300355 A collection of original short n...
3742,9780786714957,0786714956,The Mammoth Book of New Jules Verne Adventures,Mike Ashley;Eric Brown;Jules Verne,Fiction,http://books.google.com/books/content?id=KuHtl...,Written in homage to the master of science fic...,2005.0,3.68,498.0,29.0,The Mammoth Book of New Jules Verne Adventures,9780786714957 Written in homage to the master ...
3746,9780786719051,0786719052,The Mammoth Book of Golden Age Science Fiction,Isaac Asimov;Charles G. Waugh;Martin Harry Gre...,Fiction,http://books.google.com/books/content?id=Ihn4A...,"The Golden Age of Science Fiction, from the ea...",2007.0,3.91,512.0,122.0,The Mammoth Book of Golden Age Science Fiction,9780786719051 The Golden Age of Science Fictio...
3893,9780806133638,0806133635,Selections from Homer's Iliad,Homer,Literary Criticism,http://books.google.com/books/content?id=nY-5r...,"First published in 1903, Selections from Homer...",2001.0,4.39,522.0,64.0,Selections from Homer's Iliad: With an Introdu...,"9780806133638 First published in 1903, Selecti..."
3954,9780812509670,0812509676,A Fabulous Formless Darkness,David G. Hartwell,Fiction,NaN,Originally published as part of The Dark Desce...,1992.0,4.21,608.0,33.0,A Fabulous Formless Darkness,9780812509670 Originally published as part of ...
4150,9780870610639,0870610635,Summa Theologica,Thomas Aquinas,"Theology, Doctrinal",http://books.google.com/books/content?id=l9R4x...,Creating a summary of all human knowledge may ...,2000.0,4.10,3020.0,2673.0,Summa Theologica: Complete 5-Volume Set,9780870610639 Creating a summary of all human ...
4257,9780939682041,0939682044,Situationist International Anthology,Ken Knabb,Art,http://books.google.com/books/content?id=ts_dA...,The essential source book for anyone wanting t...,2006.0,4.25,532.0,662.0,Situationist International Anthology,9780939682041 The essential source book for an...
4340,9781400040308,1400040302,A Madman Dreams of Turing Machines,Janna Levin,Fiction,http://books.google.com/books/content?id=EwQi6...,"In a saga of genius, madness, and seminal scie...",2006.0,3.68,230.0,1098.0,A Madman Dreams of Turing Machines,"9781400040308 In a saga of genius, madness, an..."
4456,9781405203944,1405203943,The Mystery of the Disappearing Cat,Enid Blyton,Cats,http://books.google.com/books/content?id=V6aEA...,A fantastic children’s crime story from the wo...,1944.0,3.94,232.0,1638.0,The Mystery of the Disappearing Cat,9781405203944 A fantastic children’s crime sto...
4457,9781405203951,1405203951,The Mystery of the Secret Room,Enid Blyton,Children's stories,http://books.google.com/books/content?id=msjbA...,A fantastic children’s crime story from the wo...,2009.0,4.04,217.0,2258.0,The Mystery of the Secret Room,9781405203951 A fantastic children’s crime sto...
5121,9781896597669,1896597661,"Acme Novelty Datebook, Volume One",Chris Ware,Comics & Graphic Novels,http://books.google.com/books/content?id=2my-t...,Acclaimed cartoonist Chris Ware reveals the ou...,2013.0,4.17,208.0,494.0,"Acme Novelty Datebook, Volume One: Volume One",9781896597669 Acclaimed cartoonist Chris Ware ...
5147,9781932100563,1932100563,The Anthology at the End of the Universe,Glenn Yeffeth,Literary Criticism,http://books.google.com/books/content?id=R7y1P...,A selection of essays dealing with every aspec...,2005.0,3.85,240.0,123.0,The Anthology at the End of the Universe: Lead...,9781932100563 A selection of essays dealing wi...